# Book settings
title: Spatial Data Science 
author: Ilya Zaslavsky, Kaushik Ganapathy and Eric Yu
logo: images/blank.png
copyright: "2020"
repository:
  url                       : https://github.com/ery010/spatial-data-science


execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  exclude_patterns          : ['mp*.ipynb', 'hw*.ipynb']  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

html:
  favicon: images/logo.png
  home_page_in_navbar: false
launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

latex:
  latex_documents:
    targetname: book.tex
